merchant/modules/common/controllers/LocalAreaController.php
<?php

namespace addons\TinyShop\merchant\modules\common\controllers;

use Yii;
use common\traits\MerchantCurd;
use addons\TinyShop\common\models\common\LocalArea;
use addons\TinyShop\merchant\controllers\BaseController;

/**
 * Class LocalAreaController
 * @package addons\TinyShop\merchant\modules\common\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class LocalAreaController extends BaseController
{
    use MerchantCurd;

    /**
     * @var LocalArea
     */
    public $modelClass = LocalArea::class;

    /**
     * 编辑/创建
     *
     * @return mixed
     */
    public function actionEdit()
    {
        $model = $this->findModel($this->getMerchantId());
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->message('保存成功', $this->redirect(['edit']));
        }

        return $this->render($this->action->id, [
            'model' => $model,
        ]);
    }

    /**
     * 返回模型
     *
     * @param $id
     * @return \yii\db\ActiveRecord
     */
    protected function findModel($id)
    {
        /* @var $model \yii\db\ActiveRecord */
        if (empty(($model = $this->modelClass::findOne(['merchant_id' => $id])))) {
            $model = new $this->modelClass;
            return $model->loadDefaultValues();
        }

        return $model;
    }
}

merchant/modules/common/controllers/LocalConfigController.php
<?php

namespace addons\TinyShop\merchant\modules\common\controllers;

use Yii;
use common\helpers\ArrayHelper;
use common\helpers\DateHelper;
use common\enums\StatusEnum;
use common\traits\MerchantCurd;
use addons\TinyShop\common\models\common\LocalConfig;
use addons\TinyShop\merchant\controllers\BaseController;

/**
 * Class LocalConfigController
 * @package addons\TinyShop\merchant\modules\common\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class LocalConfigController extends BaseController
{
    use MerchantCurd;

    /**
     * @var LocalConfig
     */
    public $modelClass = LocalConfig::class;

    /**
     * 编辑/创建
     *
     * @return mixed
     */
    public function actionEdit()
    {
        $model = $this->findModel($this->getMerchantId());
        $model->is_start = StatusEnum::ENABLED;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->message('保存成功', $this->redirect(['edit']));
        }

        $section = DateHelper::formatHours(ArrayHelper::numBetween(0, 86400, true, 1800));

        return $this->render($this->action->id, [
            'model' => $model,
            'section' => $section,
        ]);
    }

    /**
     * 返回模型
     *
     * @param $id
     * @return \yii\db\ActiveRecord
     */
    protected function findModel($id)
    {
        /* @var $model \yii\db\ActiveRecord */
        if (empty(($model = $this->modelClass::findOne(['merchant_id' => $id, 'is_start' => StatusEnum::ENABLED])))) {
            $model = new $this->modelClass;
            return $model->loadDefaultValues();
        }

        return $model;
    }
}

merchant/modules/common/views/local-config/edit.php
<?php

use yii\widgets\ActiveForm;
use common\helpers\Url;
use unclead\multipleinput\MultipleInput;

$this->title = '配送费用';
$this->params['breadcrumbs'][] = ['label' => $this->title];

?>

<div class="row">
    <div class="col-sm-12">
        <div class="nav-tabs-custom">
            <?= $this->render('../common/_express_nav', [
                'type' => 'local-distribution',
            ]) ?>
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="tab-pane active">
                        <nav class="nav-tabs-child">
                            <ul>
                                <li class="selected"><a href="<?= Url::to(['local-config/edit']) ?>">配送时间及费用</a></li>
                                <li><a href="<?= Url::to(['local-area/edit']) ?>">同城配送地区</a></li>
                            </ul>
                        </nav>
                        <div class="box">
                            <?php $form = ActiveForm::begin([
                                'fieldConfig' => [
                                    'template' => "<div class='row'><div class='col-sm-2 text-right'>{label}</div><div class='col-sm-10'>{input}\n{hint}\n{error}</div></div>",
                                ],
                            ]); ?>
                            <!-- /.box-header -->
                            <div class="box-body table-responsive">
                                <div class="form-group">
                                    <?= $form->field($model, 'auto_order_receiving')->radioList(\common\enums\WhetherEnum::getMap()); ?>
                                    <?= $form->field($model, 'order_money')->textInput(); ?>
                                    <?= $form->field($model, 'freight')->textInput(); ?>
                                    <div class="form-group">
                                        <?= $form->field($model, 'make_day')->dropDownList(\common\helpers\ArrayHelper::numBetween(1, 15, true, 1, '天')); ?>
                                        <?= $form->field($model, 'interval_time')->dropDownList($section)->hint('用户只能选择多少时间后的上门时间'); ?>
                                        <?= $form->field($model, 'distribution_time')->widget(MultipleInput::class, [
                                            'iconSource' => 'fa',
                                            'min' => 1,
                                            'max' => 100,
                                            'columns' => [
                                                [
                                                    'name'  => 'start_time',
                                                    'title' => '开始时间',
                                                    'type'  => 'dropDownList',
                                                    'items' => $section
                                                ],
                                                [
                                                    'name'  => 'end_time',
                                                    'title' => '结束时间',
                                                    'type'  => 'dropDownList',
                                                    'items' => $section
                                                ],
                                            ]
                                        ]);
                                        ?>
                                        <div class="row">
                                            <div class="col-sm-2 text-right">
                                                <label class="control-label"></label>
                                            </div>
                                            <div class="col-sm-10">
                                                <div class="help-block">若起始时间与结束时间均未设置，则默认为该时间段不提供配送服务</div>
                                            </div>
                                        </div>
                                        <?= $form->field($model, 'shipping_fee')->widget(unclead\multipleinput\MultipleInput::class, [
                                            'iconSource' => 'fa',
                                            'max' => 20,
                                            'min' => 0,
                                            'columns' => [
                                                [
                                                    'name'  => 'order_money',
                                                    'title' => '消费金额',
                                                    'options' => [
                                                        'class' => 'input-priority'
                                                    ]
                                                ],
                                                [
                                                    'name'  => 'freight',
                                                    'title' => '配送费用',
                                                    'options' => [
                                                        'class' => 'input-priority'
                                                    ]
                                                ]
                                            ]
                                        ]);
                                        ?>
                                        <!-- /.box-body -->
                                    </div>
                                    <div class="box-footer text-center">
                                        <button class="btn btn-primary" type="submit">保存</button>
                                    </div>
                                    <?php ActiveForm::end(); ?>
                                    <!-- /.box -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>