merchant/modules/common/controllers/ExpressCompanyController.php
<?php

namespace addons\TinyShop\merchant\modules\common\controllers;

use Yii;
use common\models\base\SearchModel;
use common\enums\StatusEnum;
use common\traits\MerchantCurd;
use common\helpers\ArrayHelper;
use addons\TinyShop\common\models\common\ExpressCompany;
use addons\TinyShop\merchant\forms\CompanyAddressForm;
use addons\TinyShop\merchant\controllers\BaseController;

/**
 * 快递管理控制器
 *
 * Class ExpressCompanyController
 * @package addons\TinyShop\merchant\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class ExpressCompanyController extends BaseController
{
    use MerchantCurd;

    /**
     * @var ExpressCompany
     */
    public $modelClass = ExpressCompany::class;

    /**
     * 首页
     *
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionIndex()
    {
        $searchModel = new SearchModel([
            'model' => ExpressCompany::class,
            'scenario' => 'default',
            'partialMatchAttributes' => ['title', 'express_no', 'mobile'], // 模糊查询
            'defaultOrder' => [
                'sort' => SORT_ASC,
                'id' => SORT_DESC,
            ],
            'pageSize' => $this->pageSize,
        ]);

        $dataProvider = $searchModel
            ->search(Yii::$app->request->queryParams);
        $dataProvider->query
            ->andWhere(['>=', 'status', StatusEnum::DISABLED])
            ->andWhere(['merchant_id' => Yii::$app->services->merchant->getNotNullId()]);

        return $this->render($this->action->id, [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * @return mixed|string
     */
    public function actionAddress()
    {
        $request = Yii::$app->request;
        $model = new CompanyAddressForm();
        $model->attributes = $this->getConfig();
        if ($model->load($request->post()) && $model->validate()) {
            $this->setConfig(ArrayHelper::toArray($model));

            return $this->message('修改成功', $this->redirect(['address']));
        }

        return $this->render('address', [
            'model' => $model,
        ]);
    }
}

merchant/modules/common/controllers/ExpressFeeController.php
<?php

namespace addons\TinyShop\merchant\modules\common\controllers;

use Yii;
use yii\data\Pagination;
use common\enums\StatusEnum;
use common\helpers\ArrayHelper;
use common\helpers\ResultHelper;
use common\traits\MerchantCurd;
use addons\TinyShop\common\models\common\ExpressFee;
use addons\TinyShop\merchant\controllers\BaseController;

/**
 * 运费模板
 *
 * Class ExpressFeeController
 * @package addons\TinyShop\merchant\modules\common\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class ExpressFeeController extends BaseController
{
    use MerchantCurd;

    /**
     * @var ExpressFee
     */
    public $modelClass = ExpressFee::class;

    /**
     * 物流快递id
     *
     * @var integer
     */
    public $company_id;

    /**
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {
        parent::init();

        $this->company_id = Yii::$app->request->get('company_id');
    }

    /**
     * 首页
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $data = $this->modelClass::find()
            ->where(['>=', 'status', StatusEnum::DISABLED])
            ->andWhere(['company_id' => $this->company_id])
            ->andFilterWhere(['merchant_id' => $this->getMerchantId()]);
        $pages = new Pagination(['totalCount' => $data->count(), 'pageSize' => $this->pageSize]);
        $models = $data->offset($pages->offset)
            ->orderBy('is_default desc, id desc')
            ->limit($pages->limit)
            ->asArray()
            ->all();

        foreach ($models as &$model) {
            $ids = ArrayHelper::merge(explode(',', $model['province_ids']), explode(',', $model['city_ids']));
            $model['region'] = ArrayHelper::itemsMerge(Yii::$app->services->provinces->findByIds($ids), 0, 'id', 'pid', 'child');
        }

        return $this->render($this->action->id, [
            'models' => $models,
            'pages' => $pages,
            'company_id' => $this->company_id,
        ]);
    }

    /**
     * 编辑/创建
     *
     * @return mixed
     */
    public function actionEdit()
    {
        $request = Yii::$app->request;
        $id = $request->get('id', null);
        $model = $this->findModel($id);
        if ($model->load($request->post()) && $model->save()) {
            return $this->redirect(['index', 'company_id' => $this->company_id]);
        }

        // 设定禁用默认地区
        if (($default = Yii::$app->tinyShopService->expressFee->findDefaultFee($this->company_id)) && $default->id != $model->id) {
            $model->is_default = 0;
        }

        // 不可选省市区数据
        list ($allProvinceIds, $allCityIds, $allAreaIds) = Yii::$app->tinyShopService->expressFee->getNotChoose($this->company_id);

        return $this->render($this->action->id, [
            'model' => $model,
            'company_id' => $this->company_id,
            'allProvinceIds' => $allProvinceIds,
            'allCityIds' => $allCityIds,
            'allAreaIds' => $allAreaIds,
        ]);
    }

    /**
     * 伪删除
     *
     * @param $id
     * @return mixed
     */
    public function actionDestroy($id)
    {
        if (!($model = $this->modelClass::findOne($id))) {
            return $this->message("找不到数据", $this->redirect(['index', 'company_id' => $this->company_id]), 'error');
        }

        $model->status = StatusEnum::DELETE;
        if ($model->save()) {
            return $this->message("删除成功", $this->redirect(['index', 'company_id' => $this->company_id]));
        }

        return $this->message("删除失败", $this->redirect(['index', 'company_id' => $this->company_id]), 'error');
    }

    /**
     * 批量删除
     *
     * @param $id
     * @return mixed
     */
    public function actionDestroyAll()
    {
        $ids = Yii::$app->request->post('ids', []);
        if (empty($ids)) {
            return ResultHelper::json(422, '请选择需要操作的记录');
        }

        $this->modelClass::updateAll(['status' => StatusEnum::DELETE],
            ['and', ['in', 'id', $ids], ['merchant_id' => $this->getMerchantId()]]);

        return ResultHelper::json(200, '批量删除成功');
    }

    /**
     * 返回模型
     *
     * @param $id
     * @return \yii\db\ActiveRecord
     */
    protected function findModel($id)
    {
        /* @var $model \yii\db\ActiveRecord */
        if (empty($id) || empty(($model = $this->modelClass::find()->where(['id' => $id])->andWhere(['merchant_id' => $this->getMerchantId()])->one()))) {
            $model = new $this->modelClass;
            $model->company_id = $this->company_id;

            return $model->loadDefaultValues();
        }

        return $model;
    }
}

merchant/modules/common/views/express-fee/edit.php
<?php

use yii\widgets\ActiveForm;

$this->title = $model->isNewRecord ? '创建' : '编辑';
$this->params['breadcrumbs'][] = ['label' => '物流配送', 'url' => ['express-company/index']];
$this->params['breadcrumbs'][] = ['label' => '运费模板', 'url' => ['index', 'company_id' => $company_id]];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">基本信息</h3>
            </div>
            <?php $form = ActiveForm::begin([]); ?>
            <div class="box-body">
                <div class="col-lg-12">
                    <table class="table m-b-none">
                        <tbody>
                        <tr>
                            <td align="right"><div class="required"><label>模板名称</label></div></td>
                            <td><?= $form->field($model, 'title')->textInput()->label(false); ?></td>
                        </tr>
                        <tr>
                            <td align="right"><label>模板地区类型</label></td>
                            <td>
                                <?= $form->field($model, 'is_default')->dropDownList([1 => '默认地区', 0 => '指定地区'], [
                                    'disabled' => $model->is_default == true ? false : true,
                                    'id' => 'is_default',
                                ])->label(false); ?>
                                <?php if ($model->is_default == false){ ?>
                                    <?= $form->field($model, 'is_default')->hiddenInput()->label(false); ?>
                                <?php }?>
                            </td>
                        </tr>
                        <tr>
                            <td align="right">
                                <div class="required"><label>选择地区</label></div>
                            </td>
                            <td id="select"></td>
                        </tr>
                        <tr>
                            <td align="right">
                                <label>已选择地区</label>
                            </td>
                            <td>
                                <span class="js-region-info region-info"></span>
                            </td>
                        </tr>
                        <tr>
                            <td align="right"><label>按件数</label></td>
                            <td>
                                <table class="table table-bordered m-b-none">
                                    <tbody>
                                    <tr>
                                        <td width="20%" align="center">首件(件)</td>
                                        <td width="20%" align="center">首件运费(元)</td>
                                        <td width="20%" align="center">续件(件)</td>
                                        <td width="20%" align="center">续件运费(元)</td>
                                        <td width="20%" align="center">是否启用计件方式运费</td>
                                    </tr>
                                    <tr>
                                        <td><?= $form->field($model, 'bynum_snum')->textInput()->label(false); ?></td>
                                        <td><?= $form->field($model, 'bynum_sprice')->textInput()->label(false); ?></td>
                                        <td><?= $form->field($model, 'bynum_xnum')->textInput()->label(false); ?></td>
                                        <td><?= $form->field($model, 'bynum_xprice')->textInput()->label(false); ?></td>
                                        <td align="center"><?= $form->field($model, 'bynum_is_use')->checkbox(['label' => false]); ?></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td align="right"><label>按重量</label></td>
                            <td>
                                <table class="table table-bordered m-b-none">
                                    <tbody>
                                    <tr>
                                        <td width="20%" align="center">首重(kg)</td>
                                        <td width="20%" align="center">首重运费(元)</td>
                                        <td width="20%" align="center">续重(kg)</td>
                                        <td width="20%" align="center">续重运费(元)</td>
                                        <td width="20%" align="center">是否启用重量运费</td>
                                    </tr>
                                    <tr>
                                        <td><?= $form->field($model, 'weight_snum')->textInput()->label(false); ?></td>
                                        <td><?= $form->field($model, 'weight_sprice')->textInput()->label(false); ?></td>
                                        <td><?= $form->field($model, 'weight_xnum')->textInput()->label(false); ?></td>
                                        <td><?= $form->field($model, 'weight_xprice')->textInput()->label(false); ?></td>
                                        <td align="center"><?= $form->field($model, 'weight_is_use')->checkbox(['label' => false]); ?></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td align="right"><label>按体积</label></td>
                            <td>
                                <table class="table table-bordered m-b-none">
                                    <tbody>
                                    <tr>
                                        <td width="20%" align="center">首体积量(m³)</td>
                                        <td width="20%" align="center">首体积运费(元)</td>
                                        <td width="20%" align="center">续体积量(m³)</td>
                                        <td width="20%" align="center">续体积运费(元)</td>
                                        <td width="20%" align="center">是否启用体积计算运费</td>
                                    </tr>
                                    <tr>
                                        <td><?= $form->field($model, 'volume_snum')->textInput()->label(false); ?></td>
                                        <td><?= $form->field($model, 'volume_sprice')->textInput()->label(false); ?></td>
                                        <td><?= $form->field($model, 'volume_xnum')->textInput()->label(false); ?></td>
                                        <td><?= $form->field($model, 'volume_xprice')->textInput()->label(false); ?></td>
                                        <td align="center"><?= $form->field($model, 'volume_is_use')->checkbox(['label' => false]); ?></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="box-footer text-center">
                <button class="btn btn-primary" type="submit">保存</button>
                <span class="btn btn-white" onclick="history.go(-1)">返回</span>
            </div>
            <!-- 地区选择工具 -->
            <?= \common\widgets\area\Area::widget([
                'model' => $model,
                'form' => $form,
                'notChooseProvinceIds' => $allProvinceIds,
                'notChooseCityIds' => $allCityIds,
                'notChooseAreaIds' => $allAreaIds,
            ])?>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

<script>
    var allBtn = '<a class="btn btn-default btn-sm" href="javascript:void(0);">默认地区(全国)</a>';
    var assignBtn = '<a class="js-select-city btn btn-primary btn-sm" data-toggle="modal" data-target="#ajaxModalLgForExpress">指定地区城市</a>';

    $(document).ready(function () {
        if ($('#is_default').val() == true) {
            $('#select').html(allBtn);
        } else {
            $('#select').html(assignBtn);
        }
    });

    $('#is_default').change(function () {
        if ($(this).val() == true) {
            $('#select').html(allBtn);
            $(".js-regions input[type='checkbox']").prop("checked", false);
        } else {
            $('#select').html(assignBtn);
        }
    });
</script>

merchant/modules/common/views/express-fee/index.php
<?php

use yii\widgets\LinkPager;
use common\helpers\Url;
use common\helpers\Html;

$this->title = '运费模板';
$this->params['breadcrumbs'][] = ['label' => '物流配送', 'url' => ['express-company/index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">
    <div class="col-12 col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?= $this->title; ?></h3>
                <div class="box-tools">
                    <?= Html::a('<i class="fa fa-trash-o fa-lg"></i> 批量删除</a>', "javascript:void(0);", ['class' => 'btn btn-white btn-sm deleteAll']) ?>
                    <?= Html::create(['edit', 'company_id' => $company_id]); ?>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
                <?php foreach ($models as $model){ ?>
                    <table class="table table-bordered m-t-lg">
                        <tbody>
                        <tr class="info" style="background-color: #ecf0f5;">
                            <td colspan="6">
                                <?php if ($model['is_default'] != true) { ?>
                                    <?= Html::checkbox('fee_id', false, ['value' => $model['id']])?>
                                <?php } ?>
                                <span><?= $model['title']; ?></span>
                                <div class="float-right">
                                    <?= Html::a('编辑', ['edit', 'id' => $model['id'], 'company_id' => $company_id], [
                                        'class' => 'blue'
                                    ]); ?>
                                     |
                                    <?php if ($model['is_default'] != true) { ?>
                                        <?= Html::a('删除', ['destroy', 'id' => $model['id'], 'company_id' => $company_id], [
                                            'class' => 'red',
                                            'onclick' => "rfTwiceAffirm(this, '确认删除吗？', '请谨慎操作');return false;"
                                        ]); ?>
                                    <?php } ?>
                                </div>
                            </td>
                        </tr>
                        <tr class="address">
                            <td colspan="6">
                                <?php if ($model['is_default'] == true) { ?>
                                    <span>全国</span>
                                <?php } else { ?>
                                    <?php foreach ($model['region'] as $region) { ?>
                                        <span><?= $region['title']; ?></span>
                                    <?php } ?>
                                    <span class="btn btn-white btn-sm region-view" data-toggle="modal" data-target="#ajaxModalRegion" data-value=<?= json_encode($model['region']); ?>>查看详情</span>
                                <?php } ?>
                            </td>
                        </tr>
                        <tr>
                            <td align="center">按件数</td>
                            <td>
                                首件(件)：
                                <span class="red pull-right"><?= $model['bynum_snum']; ?></span>
                            </td>
                            <td>
                                首件运费(元)：
                                <span class="red pull-right"><?= $model['bynum_sprice']; ?></span>
                            </td>
                            <td>
                                续件(件)：
                                <span class="red pull-right"><?= $model['bynum_xnum']; ?></span>
                            </td>
                            <td>
                                续件运费(元)
                                <span class="red pull-right"><?= $model['bynum_xprice']; ?></span>
                            </td>
                            <td align="center">
                                <?php if ($model['bynum_is_use'] == true) { ?>
                                    <span class="green">已启用</span>
                                <?php } else { ?>
                                    <span class="red">已停用</span>
                                <?php } ?>
                            </td>
                        </tr>
                        <tr>
                            <td align="center">按重量</td>
                            <td>
                                首重(kg)：
                                <span class="red pull-right"><?= $model['weight_snum']; ?></span>
                            </td>
                            <td>
                                首重运费(元)：
                                <span class="red pull-right"><?= $model['weight_sprice']; ?></span>
                            </td>
                            <td>
                                续重(kg)：
                                <span class="red pull-right"><?= $model['weight_xnum']; ?></span>
                            </td>
                            <td>
                                续重运费(元)：
                                <span class="red pull-right"><?= $model['weight_xprice']; ?></span>
                            </td>
                            <td align="center">
                                <?php if ($model['weight_is_use'] == true) { ?>
                                    <span class="green">已启用</span>
                                <?php } else { ?>
                                    <span class="red">已停用</span>
                                <?php } ?>
                            </td>
                        </tr>
                        <tr>
                            <td align="center">按体积</td>
                            <td>
                                首体积量(m³)：
                                <span class="red pull-right"><?= $model['volume_snum']; ?></span>
                            </td>
                            <td>
                                首体积运费(元)：
                                <span class="red pull-right"><?= $model['volume_sprice']; ?></span>
                            </td>
                            <td>
                                续体积量(m³)：
                                <span class="red pull-right"><?= $model['volume_xnum']; ?></span>
                            </td>
                            <td>
                                续体积运费(元)：
                                <span class="red pull-right"><?= $model['volume_xprice']; ?></span>
                            </td>
                            <td align="center">
                                <?php if ($model['volume_is_use'] == true) { ?>
                                    <span class="green">已启用</span>
                                <?php } else { ?>
                                    <span class="red">已停用</span>
                                <?php } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                <?php } ?>

                <div class="row">
                    <div class="col-sm-12">
                        <?= LinkPager::widget([
                            'pagination' => $pages,
                        ]);?>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</div>

<div class="modal fade" id="ajaxModalRegion" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">地区详情</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body mask-address-info">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
            </div>
        </div>
    </div>
</div>

<!-- 模板 -->
<script id="region" type="text/html">
    {{each list as value i}}
    <div>
        <h3>{{value.title}}</h3>
        <ul>
            {{each value.child as item i}}
            <li>{{item.title}}</li>
            {{/each}}
        </ul>
    </div>
    {{/each}}
</script>

<script>
    // 视图详情
    $('.region-view').click(function () {
        var newData = [];
        newData['list'] = $(this).data('value');

        var html = template('region', newData);
        $('.modal-body').html(html);
    });

    // 批量删除
    $('.deleteAll').click(function () {
        var feeIds = [];
        $("tbody input[type='checkbox']:checked").each(function() {
            if (!isNaN($(this).val())) {
                feeIds.push($(this).val());
            }
        });

        if (feeIds.length == 0) {
            rfWarning('请选择需要操作的记录');
        } else {
            $.ajax({
                type : "post",
                url : "<?= Url::to(['destroy-all'])?>",
                dataType : "json",
                data : {ids: feeIds},
                success: function(data){
                    if (data.code == 200) {
                        swal(data.message, {
                            title: data.message,
                            text  : '小手一抖就打开了一个框',
                            type  : "success"
                        }).then(function (value) {
                            location.reload();
                        });
                    } else {
                        rfWarning(data.message);
                    }
                }
            });
        }
    })
</script>